2024-09-15 11:43:23,513 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:43:33,528 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:43:43,539 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:43:53,549 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:44:03,559 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:44:13,571 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:44:23,581 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:44:33,591 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:44:43,603 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:44:53,612 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:45:03,623 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:45:13,636 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:45:23,644 - ValveController - ERROR - MQTT connection failed: timed out
Traceback (most recent call last):
  File "/app/valves_node.py", line 62, in connect_mqtt
    self.client.connect(self.broker_host, self.broker_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 856, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    sock.connect(sa)
socket.timeout: timed out
2024-09-15 11:45:58,632 - ValveController - INFO - Connected to MQTT broker with result code Success
2024-09-15 11:45:58,633 - ValveController - INFO - Subscribed to topic: device1/valves/1
2024-09-15 11:45:58,634 - ValveController - INFO - Subscribed to topic: device1/valves/2
2024-09-15 11:45:58,638 - ValveController - INFO - Subscribed to topic: device1/valves/3
2024-09-15 11:45:58,639 - ValveController - INFO - Subscribed to topic: device1/valves/4
2024-09-15 11:45:58,639 - ValveController - INFO - Subscribed to topic: device1/valves/5
2024-09-15 11:45:58,642 - ValveController - INFO - Subscribed to topic: device1/valves/6
2024-09-15 11:57:11,993 - ValveController - INFO - Connected to MQTT broker with result code Success
2024-09-15 11:57:11,994 - ValveController - INFO - Subscribed to topic: device1/valves/1
2024-09-15 11:57:11,994 - ValveController - INFO - Subscribed to topic: device1/valves/2
2024-09-15 11:57:11,995 - ValveController - INFO - Subscribed to topic: device1/valves/3
2024-09-15 11:57:11,996 - ValveController - INFO - Subscribed to topic: device1/valves/4
2024-09-15 11:57:11,996 - ValveController - INFO - Subscribed to topic: device1/valves/5
2024-09-15 11:57:11,997 - ValveController - INFO - Subscribed to topic: device1/valves/6
2024-09-15 11:57:12,096 - ValveController - INFO - Valve '1' state set to 1
2024-09-15 11:57:12,097 - ValveController - INFO - Valve '2' state set to 1
2024-09-15 11:57:12,097 - ValveController - INFO - Valve '3' state set to 1
2024-09-15 11:57:12,099 - ValveController - INFO - Valve '4' state set to 1
2024-09-15 11:57:12,101 - ValveController - INFO - Valve '5' state set to 0
2024-09-15 11:57:12,103 - ValveController - INFO - Valve '6' state set to 1
2024-09-15 12:00:18,054 - ValveController - INFO - Connected to MQTT broker with result code Success
2024-09-15 12:00:18,055 - ValveController - INFO - Subscribed to topic: device1/valves/1
2024-09-15 12:00:18,055 - ValveController - INFO - Subscribed to topic: device1/valves/2
2024-09-15 12:00:18,056 - ValveController - INFO - Subscribed to topic: device1/valves/3
2024-09-15 12:00:18,057 - ValveController - INFO - Subscribed to topic: device1/valves/4
2024-09-15 12:00:18,057 - ValveController - INFO - Subscribed to topic: device1/valves/5
2024-09-15 12:00:18,058 - ValveController - INFO - Subscribed to topic: device1/valves/6
2024-09-15 12:00:27,658 - ValveController - INFO - Valve '1' state set to 1
2024-09-15 12:00:27,686 - ValveController - INFO - Valve '2' state set to 0
2024-09-15 12:00:27,688 - ValveController - INFO - Valve '3' state set to 1
2024-09-15 12:00:27,689 - ValveController - INFO - Valve '4' state set to 0
2024-09-15 12:00:30,999 - ValveController - INFO - Valve '1' state set to 1
2024-09-15 12:00:31,002 - ValveController - INFO - Valve '2' state set to 1
2024-09-15 12:00:31,004 - ValveController - INFO - Valve '3' state set to 1
2024-09-15 12:00:31,006 - ValveController - INFO - Valve '4' state set to 1
2024-09-15 12:00:31,007 - ValveController - INFO - Valve '5' state set to 1
2024-09-15 12:00:31,009 - ValveController - INFO - Valve '6' state set to 1
2024-09-15 12:00:35,035 - ValveController - INFO - Valve '1' state set to 1
2024-09-15 12:00:35,038 - ValveController - INFO - Valve '2' state set to 1
2024-09-15 12:00:35,039 - ValveController - INFO - Valve '3' state set to 1
2024-09-15 12:00:35,039 - ValveController - INFO - Valve '4' state set to 1
2024-09-15 12:00:35,040 - ValveController - INFO - Valve '5' state set to 0
2024-09-15 12:00:35,041 - ValveController - INFO - Valve '6' state set to 1
